spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/commerce?characterEncoding=UTF-8
    username: root
    password: zerobase

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  jwt:
    secret: emVyb2Jhc2VfY29tbWVyY2VfbWlzc2lvbl9pbWd5dXJpXzA1MTdfc2VjcmV0X2tleQ==

logging:
  config: classpath:logback-spring.xml
